---
title: "Final Project Capstone"
author: "Puja Singh"
date: "January 24, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Project Requirements

The goal of this exercise is to create a product to highlight the prediction algorithm that you have built and to provide an interface that can be accessed by others. For this project you must submit:

1. A Shiny app that takes as input a phrase (multiple words) in a text box input and outputs a prediction of the next word.

2. A slide deck consisting of no more than 5 slides created with R Studio Presenter pitching your algorithm and app as if you were presenting to your boss or an investor.

A key point here is that the predictive model must be small enough to load onto the Shiny server. So pay attention to model size when creating and uploading your model.


## Application Interface

The User Input panel on the left contains three items. First is a text box to enter the phrase you'd like analyzed. Second is a drop down menu where you can select the maximum number of words to return. Third is a button, 'Analyze Text', that is the algorithm's call to action and initiates the analysis. Analysis will only be performed upon pressing this button.

The algorithm returns three things. First the original text that the user provided, second is the filtered text provided to the algorithm, third is a table. In the lefthand column of this table we have the predicted words, in the right hand column we have the log probability. The table is sorted from the most likely word in the first row to the least likely in the last row.



## Shiny App & Presenter: 

1. shiny App can be find here. <https://finalpro.shinyapps.io/PrediNext/>
2. Source code. <https://github.com/b4puja/Dasta-Capstone>

##The Application Guideline
This Application has 3 menu item
1. Interface for user to key-in Text/phrases input
2. Interface to display the word prediction result
3. Description of the application

How to use: 4 Simple Steps only
1. Key in text/phrases using textInput field
2. Choose the number of words either 1 or 3 or 5 to predict using numericInput
3. Click Submit Button,
4. View the Results (Next Word Prediction).

